KIND_SHELL = "SHELL"
KIND_ARTIFACT = "ARTIFACT"
KIND_DOCKER_BUILD = "DOCKER_BUILD"
KIND_DOCKER_RUN = "DOCKER_RUN"
KIND_NPM = "NPM"
TYPES = [KIND_SHELL, KIND_ARTIFACT, KIND_DOCKER_BUILD, KIND_DOCKER_RUN, KIND_NPM]

PENDING = "PENDING"
DONE = "DONE"
ABORT = "ABORT"
