KIND_SHELL = "SHELL"
KIND_ARTIFACT = "ARTIFACT"
KIND_DOWNLOAD = "DOWNLOAD"
KIND_DOCKER_BUILD = "DOCKER_BUILD"
KIND_DOCKER_RUN = "DOCKER_RUN"
KIND_NPM = "NPM"
TYPES = [KIND_SHELL, KIND_ARTIFACT, KIND_DOWNLOAD, KIND_DOCKER_BUILD, KIND_DOCKER_RUN, KIND_NPM]
TYPES_DESCRIPTION = {}
TYPES_DESCRIPTION[KIND_ARTIFACT] = '{"job": "gitlab_job_ref"}'
TYPES_DESCRIPTION[KIND_SHELL] = "${artifact}"

PENDING = "PENDING"
DONE = "DONE"
ABORT = "ABORT"
